### ISSUE TITLE
Allow setting default dark/light for the switcher mode without js

### ISSUE THREAD

**Issue by eugenesvk** [Jieiku/abridge#125]
In the `switcher` mode when the client disables JS, the mode is always dark since afaik the css rules use the `:not(.light)` catch-all, which is used in the absence of any code getting/setting the page's `light` property.

It would be nice if you could instead have proper `.light` and `.dark` modes and then add the dark/light styling to the unstyled root depending on a `COPY-TO-ROOT-SASS/abridge.scss` user editable variable. This way you can still use the switcher as usual, but have a user-customizable fallback

(this could also potentially be useful if you move from a binary set of modes to include, e.g., `.sepia`)

**Comment by Jieiku** [comment]
The idea behind using `:not(.light)` was to have zero unstyled flash of color for anyone that has disabled js or has not played with the switcher button. As you have noticed it does force you into a default theme. In my case I use abridge for a technical blog and prefer the dark mode anyway which is why I made it the default in the case that JS is disabled.

Most if not all Zola themes that have a style selector with at least some Flash of inaccurate color theme.

https://css-tricks.com/flash-of-inaccurate-color-theme-fart/

I did the best that I could to minimize this affect for abridge, by loading the tiny theme.js alone as the first file in the Head so that it would be processed as quickly as possible.

I spent more time than I care to admit working on this initially, as even well known css frameworks that have been around for years seemed to have this issue pretty badly.

I wonder if instead of `:not(.light)` we could just use an ambiguous definition `:not(.changed)`

.changed could represent whichever color is NOT the default, and then the default could be set depending on a `COPY-TO-ROOT-SASS/abridge.scss` user editable variable.

This would resolve being able to set a user defined fallback, it would not resolve moving away from a binary set of modes, but unless that could be done without FART, then I don't think it would be worthwhile anyway.

Let me know your thoughts on this. I appreciate the ideas!

**Comment by eugenesvk** [comment]
> when JS is disabled, or when you have NOT yet clicked the switcher, you are not actually FORCED into dark mode, you are forced into your OS/Browser preference

that's what I don't get
In this abridge.scss code (with exras removed) when you use a swither button, so you set `$abridgeMode	: "switcher"`, then you're forced into the dark mode due to it being the only condition that matches without JS, right?
```scss
@if $abridgeMode == "auto" {
} @else if $abridgeMode == "dark" {
} @else if $abridgeMode == "light" {
} @else {//switcher (default)
  :root {
    @include font;
    @include root;
  }
  :root:not(.light) { @include colors.dark( $dark... );}
  :root.light       { @include colors.light($light...);}
}
```

The broswer preferences are only accounted for in the `"auto"` mode with `  @media (prefers-color-scheme: light) {`, right?

So I just thought instead of this you could do something like 
```scss
} @else {//switcher (default)
  :root {
    @include font;
    @include root;
    @if $abridgeSwitcherDefaultMode == "light" { @include colors.light($light...);
    } @else {                                    @include colors.dark ($dark... );}}
  :root.dark {                                  @include colors.dark ($dark... );}
  :root.light {                                  @include colors.light($light...);}
```

then if there is no JS, the is no `root` modifier set in the storage, so you only get the default `root` style, which would depend on your user variable

> I am hesitant to change the way this works, because I want to avoid unstyled flash of color the best that I can.

I agree that flashes are worse than a dark default without JS

**Comment by Jieiku** [comment]
ah, your absolutely right.

You are forced into dark mode if JS is disabled.... I worked on this so long ago that I thought I had done it differently.

I am going to see what I can do about this.

**Comment by Jieiku** [comment]
I had an idea to use .switched as the class name instead of .light, then we would just set the default and switch colors appropriately, and still use the :root:not(.switch)

however the js that handles this assumes that the default is dark mode, and then it applies the .light class only if the media query does not match dark preference:

https://github.com/Jieiku/abridge/blob/refactor/static/js/theme.js

**Comment by eugenesvk** [comment]
> By only using the localstorage for one of the two themes, you ensure that one of the two themes works flawlessly, because local storage never even comes into the picture.

But if you have separate themes in the switcher and the default theme in the root, you could still have that, the default will work flawlessly without any JS, and then JS will set a different theme (dark/light/sepia/whatever) that will just override the default

**Comment by Jieiku** [comment]
Yes your right, but still have to work this out, it works on the basis that dark mode is the default:

https://github.com/Jieiku/abridge/blob/refactor/static/js/theme.js

```js
!window.matchMedia("(prefers-color-scheme: dark)").matches
```

I will try a few things and see what I can come up with.

**Comment by Jieiku** [comment]
prefers-color-scheme: dark and prefers-color-scheme: light are browser features

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Changing the default theme is css is simple, as you have outlined, but when you flip flop dark to light as the default then the javascript has to account for that.

One Idea I had was to have a value in config.toml  prefersdark = true/false, depending on this value it would load the corresponding js file, this solution would work, because all themes are going to be considered light or dark overall.

theme.js is already loaded separately in the head to optimize load speed so that it can prevent flash of unstyled color as quickly as possible, so swapping this file out for a light or dark version is not an issue.

The problem is with theme_button.js which currently gets bundled in with the rest of the javascript. I don't want to add this code to the theme.js because that file needs to load as quickly as possible, but I could separately theme_button.js from the main bundle, it would result in one additional server request though.

The ideal solution is if Zola supported building js files we could arbitrarily include whatever js code we want. I opened a ticket about this, and started trying to implement this in Zola, but its a little tricky and I just have not had time yet to work on it.

here is that thread:  https://github.com/getzola/zola/issues/2167 and https://github.com/getzola/zola/issues/2167#issuecomment-1520746832

**Comment by Jieiku** [comment]
This is now complete: https://github.com/Jieiku/abridge/commit/631ec157c04e2643969303d409cce758125449d3

Because Zola does not support generating js files from a template, we have to set TWO config values, one in the scss to set the default color theme, and another in config.toml to load the appropriate theme.js file.

https://github.com/Jieiku/abridge/blob/631ec157c04e2643969303d409cce758125449d3/COPY-TO-ROOT-SASS/abridge.scss#L13

https://github.com/Jieiku/abridge/blob/631ec157c04e2643969303d409cce758125449d3/config.toml#L205
