### ISSUE TITLE
[Feature Request] Prefix all posts' urls with "posts/"

### ISSUE THREAD

**Issue by samueloph** [Jieiku/abridge#128]
Looks like there's no configuration setting that lets me prefix all posts with "posts/", I like this behavior because it makes the urls more descriptive.

Example: Instead of url like "example.com/post-title", to have "example.com/posts/post-title"

Also allowing for the date to be used as a prefix might be useful for other users too, example "example.com/2023/07/16/post-title".

Edit- I could accomplish something similar with https://peterbabic.dev/blog/setting-url-prefix-in-zola/

**Comment by Jieiku** [comment]
This is related for the date: https://github.com/Jieiku/abridge/issues/97

I never used a url prefix, there might be more than one way to accomplish that.

**Comment by Jieiku** [comment]
Both the archive and the index templates can be referenced from a section, work for that was done here: https://github.com/Jieiku/abridge/issues/118

I just made the example content in the abridge refactor tree so that it will show the two different solutions.

a transparent section will essentially add the content to the main content directory but using the path of that section. (this is what I did for content/posts)

A regular section can also be used, this is what I did for content/blog, the _index.md in that directory points to the index.html template, but the archive.html template also supports sections.
