### ISSUE TITLE
"X minute read"

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#14]
Could we receive a meta option to add a reading time estimate on blog posts?

Similar to:
[![2022-05-06_06-15](https://user-images.githubusercontent.com/48108917/167113270-7d9e4954-947c-4ed6-a713-b0764eb2a4cd.png)]()

**Comment by Jieiku** [comment]
I can add this as an option, will add it today.

**Comment by Jieiku** [comment]
That looks really similar to what AdiDoks does:
https://adidoks.netlify.app/blog/

Then notice in the actual article its the same:
https://adidoks.netlify.app/blog/hello-world/

One thing they do NOT do (atleast by default) is display the categories or tags.

How are you wanting this text to look? and do you want it to look the same on both the index and the page details?

I can add multiple macros and some config options so that it can be displayed a variety of ways, this is all handled in the file: `abridge/templates/macros`

**Comment by simbleau** [comment]
Definitely on the index page.

I am indifferent otherwise. :)

**Comment by Jieiku** [comment]
ok, I just about have this ready, will commit after I test a couple things.

**Comment by Jieiku** [comment]
This is now finished.
