### ISSUE TITLE
Site description appears to be out of order on mobile

### ISSUE THREAD

**Issue by tlivolsi94** [Jieiku/abridge#156]
![Screenshot_20231113-070432](https://github.com/Jieiku/abridge/assets/144085285/9d1e4493-258b-4797-9070-92cb5ff1aa8b)

Let me know if you need anything else from me! Thanks for the great theme.

**Comment by Jieiku** [comment]
Thank you very much for the report, certainly does not looks right to me. The reason is because of the way the flex wrap works. Technically the sitedesc is the lowest item in the site sources, so when it wraps it is still the lowest item.

The sitedesc could possibly be moved into the logo div, it would then stick to the bottom of the logo on wrap, but the sitedesc would also wrap even in desktop view instead of using the full width of the page as it does now.

Mobile views often hide or omit certain things to make more efficient use of the smaller screen, so this is what I have opted to do. Similar to what I do for the recent posts block: https://github.com/Jieiku/abridge/commit/c8fcaa926a3820c72b6d6d3b04d74eaaa43f5f69
