### ISSUE TITLE
 Invalid CSS error running zola serve

### ISSUE THREAD

**Issue by Brandon689** [Jieiku/abridge#157]
Error: Failed to serve the site
Error: Error: Invalid CSS after "$dark: colors": expected expression (e.g. 1px, bold), was ".color($color,true,"
        on line 106:14 of //?/C:/Code3/DecSPEEDHERO/abridge-master/sass/abridge.scss
>> $dark: colors.color($color,true,$csd,$f1d,$f2d,$c1d,$c2d,$c3d,$c4d,$a1d,$a2d

**Comment by Jieiku** [comment]
It appears you are using windows, and I am particularly interested in having it work for windows users, but I have less experience with windows. Can you walk me through how to reproduce the problem?

What is your version of windows. and what things do I need to click or do in order to run into this same error.

**Comment by Brandon689** [comment]
Windows 11
Choco package manager
download repo, run zola serve in it

I will try building zola from source so its updated and see if that changes it.

**Comment by Jieiku** [comment]
yeah, there is a minimum requirement for Zola.

I do know that Zola 0.17 or later is a very hard dependency requirement for Abridge. This is because of the css dependency used in Zola. I discussed it some here: https://github.com/getzola/after-dark/pull/42#issue-1698229310

**Comment by Brandon689** [comment]
Yes, this solved my problem. Every single time I have used choco to install something, it has backfired. I still had 0.16x version Its so outdated.
