### ISSUE TITLE
Add SEO images

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#16]
Needs support for the multi-plat SEO images
google if not understood:
```
android-chrome-192x192.png
android-chrome-512x512.png
apple-touch.icon.png
etc...
```

**Comment by Jieiku** [comment]
This was already on my todo list. In fact I need to review ALL of the seo related tags.

I left a couple notes in the readme about needing to review everything related to SEO.

On initial commit I researched the seo tags, and added most of them, but some of them need to use specific post matter instead of general site values.

**Comment by Jieiku** [comment]
pretty sure I got them all!

LOTS of changes in the config.toml as a result of cleaning up the whitespace and moving head code from base.html into a macro.
