### ISSUE TITLE
Generate whole post content on RSS/Atom feed instead of just a summary

### ISSUE THREAD

**Issue by DaniSancas** [Jieiku/abridge#161]
Hi!

I was wondering if there's a way to allow the feed to include the whole post instead of just a summary. Some people usually don't want to leave their RSS reader if they they are allowed to view the whole post (and I think it's an empowering thing).

So, is there a current option (couldn't find it in the `config.toml` or plans to implement it soon?

Thank you very much!

**Comment by Jieiku** [comment]
I simply enabled the rss feed option of zola. I wonder if any of the other themes show the whole feed?

I would check Zola documentation and also check if any of the other themes are somehow able to provide the entire rss feed instead of just a summary.

This may end up being a feature request for upstream zola.

I do not have time at the moment to research it, so feel free to see what you can find out, if another theme is able to do it then let me know which one, otherwise if it seems like all themes are only displaying a summary then a feature request would need to be opened with Zola.

I can look into this when I get some free time but i am really busy for a while with a few other projects.

**Comment by DaniSancas** [comment]
Thanks for your comment!

I've looking for it in Zola Docs and I'd say the only way its by overwriting the `atom.xml` template: https://github.com/getzola/zola/blob/master/components/templates/src/builtins/atom.xml#L46-L50

There's nothing related to that in the Docs, but the template seems to be easily modified.

I think we can close the issue 😉
