### ISSUE TITLE
Update Observatory Mozilla

### ISSUE THREAD

**Issue by m00sp** [Jieiku/abridge#203]
Mozillla Observatory is deprecated, update to https://developer.mozilla.org/en-US/observatory/analyze?host=abridge.netlify.app

**Comment by Jieiku** [comment]
Abridge currently scores the same score of 130 at the new observatory.

The old observatory was available on github, and you could run your own local copy of it.

One of the problems with both the old and the new observatory is that they return the score of the base domain instead of including the folder path. With the old one you can atleast modify it to work.

I got into some of the details here: https://github.com/Jieiku/zola-themes-benchmarks/issues/4

I am hoping that maybe it is possible to self host the newer observatory as well, but I am not sure about that, where is the repository for the code?

My self hosted copy was pulled directly from github, and it appears to be on commit https://github.com/mozilla/observatory-cli/commit/8e3f37c818e8e9fad66678fe9af15a595130f83a (December 2022)

Which so happens to be the latest commit on the Master branch of that repo.

**Comment by Jieiku** [comment]
Since I am already tracking this issue here: https://github.com/Jieiku/zola-themes-benchmarks/issues/4

I am going to go ahead and close this one, anyone that finds this issue will hopefully find their way to my other repo where I have the issue open.

**Comment by m00sp** [comment]
Thank you so much. Here you have what you asked.
The old observatory repo, which es deprecated and will be sunsetted this month:
https://github.com/mozilla/http-observatory-website/
And the new repo:
https://github.com/mdn/content/
And here is the pr with the details for you to see, if o dont undestood worng:
https://github.com/mdn/content/pull/33793
Have a nice day

**Comment by Jieiku** [comment]
Based on the repos you links, its looks like maybe it is just the website component that changed, and I use the CLI instead so it should not be an issue :)
