### ISSUE TITLE
Should the files changed by `npm run abridge` not be committed?

### ISSUE THREAD

**Issue by Kleidukos** [Jieiku/abridge#204]
When I run `npm run abridge` I see the following files are changed:

* package_abridge.js
* static/js/abridge.min.js
* static/js/abridge_nopwa.min.js
* static/js/sw_load.js

They seem related to the live, deployed version of the blog, live in `static/`, yet somehow they are not listed in the `.gitignore` file. 

I have elected to ignore them in my repository but I wanted to know what was the intended usage.

Cheers.

**Comment by Jieiku** [comment]
You can read more about the javascript files here: https://abridge.pages.dev/overview-abridge/#javascript-files

- abridge.min.js - is a bundled and minified file of all the individual js files, results in a smaller size and fewer requests.
- abridge_nopwa.min.js - is a bundled and minified file of all the individual js files, results in a smaller size and fewer requests. The difference with this one is that it does not include the files used by the pwa, Having this file is useful because then if a user that knows nothing about node, and wants to only use Zola without npm, they can simply set `pwa = false` in `config.toml`
- static/js/sw_load.js - This is the service worker loader for the PWA. This file generally should not change, except when you increment the `pwa_VER` in `config.toml`
- package_abridge.js - This script is called by node when you run `npm run abridge`,  you can see the call to this file in `package.json`. The `package_abridge.js` file has all the logic for bundling and minifying the js files based on the settings set in config.toml. This file also handles creating the index for pagefind if you are using the pagefind search library. This file should not be changing as far as I can remember. (part of the setup steps is to copy it in place: rsync themes/abridge/package_abridge.js package_abridge.js so maybe that is the reason you see it added/changed, if the file i s changing at every run of npm run abridge then something might be wrong.)

**Comment by Kleidukos** [comment]
Thank you very much for the answer!
