### ISSUE TITLE
Excluding unused favicons from being published?

### ISSUE THREAD

**Issue by l-mb** [Jieiku/abridge#211]
Hi, thanks for the great theme.

I have found out to override my `favicon.svg` (I saw the other issues on this) via `static/favicon.svg` and the related `config.toml` setting. That's fine, and I assume that should be sufficient for all scenarios?

But `zola build` still includes the unused icons/imagery:

```
 android-chrome-192x192.png   favicon.ico   m192.png   m512.png   mstile-150x150.png
 android-chrome-512x512.png   favicon-16x16.png   m1024.png     m384.png   m72.png
 apple-touch-icon.png	      favicon-32x32.png   m128.png      m48.png    m96.png
```

And they're referenced in the `manifest/sw.js` files.

Is there a way to disable them completely?

Thanks, sorry in advance if I misunderstand something (I did try to read the docs) and some of these are required indeed.

**Comment by Jieiku** [comment]
add this to your config.toml:

```toml
ignored_static = ["apple-touch-icon.png","banner.png","safari-pinned-tab.svg","favicon*","m*.png","android-chrome*png"]
```

**Comment by Jieiku** [comment]
I did not test if this excludes it properly from `sw.js`

Will test that later this evening, but it did properly exclude them from the public folder after a zola build.

**Comment by Jieiku** [comment]
I opened a report here: https://github.com/getzola/zola/issues/2677

Short of creating empty files to override the ones in the theme I have no idea if this is possible.

**Comment by l-mb** [comment]
Thank you very much, appreciated!

**Comment by Jieiku** [comment]
I have added a new array `pwa_IGNORE_FILES` to `config.toml`  https://github.com/Jieiku/abridge/commit/05a92f2ec6e8c86baafc7d970e8c992d395b9691

You could use this value:

```toml
pwa_IGNORE_FILES = ["_headers","sw.min.js","sw.js","android-chrome-192x192.png","android-chrome-512x512.png","apple-touch-icon.png","favicon-16x16.png","favicon-32x32.png","favicon.ico","m48.png","m72.png","m96.png","m128.png","m192.png","m384.png","m512.png","m1024.png","mstile-150x150.png"]
```

The purpose of this file is to exclude files from being added to sw.js

In order to modify the `manifest.json` just copy the `manifest.json` file from the theme to your sites main static folder, your copy will override the copy in the theme, so you can modify your copy as necessary and remove whatever icons you wish.

If you create empty files in your sites main static folder, they will override the files in the theme with your empty files.

If you do these things then the files will no longer be listed in the manifest.json or sw.js files and the files that are on your site will simply be empty files.

I have no way to prevent the files from being copied over entirely, so the best you can do is override them with empty files unless zola adds provisions to ignore files within the theme, but this solution should suffice for now.
