### ISSUE TITLE
Bug: can't seem to change the main font

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#34]
I've tried importing in the fonts via config.toml file, such as "FireCode-Regular", and then modifying the font face via the theme:

```toml
fonts_load = true # used to import fonts
fonts = [
    {url = "font/FiraCode-Regular.woff2"},
]
```

```scss
:root {
  // Typography
  --ff: "FiraCode", "FiraCode-Regular", system-ui, -apple-system, "Segoe UI",
  ...
```

No avail. Do you know how I'm meant to do this? While we're at it, might want to propose README changes (that could wait for an entire README refresh) or present this as a config.toml setting.

And a follow-up (insignificant) issue would be how to change the monospace font used in code blocks from Markdown.

**Comment by Jieiku** [comment]
I just tried this and I can see the font declared in the developer console, but the font face does not seem to change on screen.

I think this is a case of css inheritance not working as expected, will have to look it over.

**Comment by simbleau** [comment]
Thanks :)

**Comment by Jieiku** [comment]
I have external font resources working now.

I am able to apply Merriweather or Montserrat font:

```toml
:root {
  // Regular Fonts used by default:
  --ff: Merriweather, Montserrat, system-ui, -apple-system, "Segoe UI", Roboto, Ubuntu, Cantarell, "Noto Sans", sans-serif;
```

Still trying to figure out why the local woff2 fonts are not working.

**Comment by Jieiku** [comment]
I think these woff2 fonts I am using might be bad, going to try a different one.

**Comment by Jieiku** [comment]
I have this working for both remove and local fonts.

for the remote fonts you can try Merriweather or Montserrat

for the local fonts you can try FiraCode or SourceCodePro

The local fonts are now loaded via the fonts.css file. For the moment this is the only way I have been able to get local fonts working. The articles I have read suggest you should be able to use the font directly without the need for the css file, but in all my testing it never works, this however does work.

If you find a different solution then let me know, otherwise this is case closed for now.

**Comment by simbleau** [comment]
Without getting into the weeds so much, I really Abridge would benefit from having colors and fonts specified in the theme's config.toml

```toml
main_font = "/path/to/font.woff2"
monospace_font = "/path/to/that.woff2"

color1 = #00ff00
...
```

obviously, if someone wants to do really advanced things like set the backup fonts then they need to create a custom theme or copy the theme.

Some reasons I'm suggesting this:
- It's common enough people probably want to do this
- Sass is difficult to override locally (or I can't figure out how to do it well), making choosing the font or colors require duplicating the theme into your own zola instance.
- `fonts_load` and `fonts` could be one setting, since loading a font implies `fonts_load` is true

**Comment by Jieiku** [comment]
Off the top of my head I dont think you can actually define colors in the config.toml because the scss files are compiled by zola.

The only way that comes to mind is hard coding colors ALL OVER the entire theme, for example

<font color="{{ config.extra.color1 }}">Welcome to my site</font>, and in my opinion hard coding colors throughout the html is not good.

For the fonts I am completely open to any pull requests or ideas. In what way did you load your fonts when you got that big delay? were you using the fonts.css file? https://github.com/Jieiku/abridge/blob/master/static/fonts.css

**Comment by simbleau** [comment]
Yep, I was loading through CSS.

**Comment by Jieiku** [comment]
I did not notice that delay, but I will do some more testing to see if the same thing is happening to me.

**Comment by simbleau** [comment]
You could clone my blog and checkout the commit starting with 53f76 (a few commits back, before I removed it all) 

I think the issue is because I loaded like 4 fonts IIRC.

( a bold font, italic font, regular font, source font )

**Comment by Jieiku** [comment]
ok I will check it out tonight.

**Comment by Jieiku** [comment]
Can you give me a link to the commit your referring to? I cannot seem to find it.

**Comment by simbleau** [comment]
https://github.com/simbleau/simbleau.github.io/tree/892b00b42807310787127aa8494298732faa394b

**Comment by Jieiku** [comment]
Ok, I made some big changes. I was unsure of the licensing on CeraPro so I bundled PT Sans instead which is a very similar font.

Now each Skin has its own Font includes file, in the main skin file this import can be easily commented out to disable loading of the local fonts. With this setup I was seeing first contentful pain 0.9s but please test these changes and let me know what you see.

Also I set your theme to have these fonts enabled, but feel free to comment out the font include line if you dont like what you see and I will merge it.

```scss
@import "skins/blue_fonts"; // Fonts
```

**Comment by simbleau** [comment]
Hmm, reviewing now.

Immediate thoughts though - I wanted to make bluelight identical to Abridge, except use blue as the main color instead of orange. Therefore, the font should be shared (Jost).

My goal was to have this behavior for anyone - but I wanted to override the font locally.

**Comment by Jieiku** [comment]
One moment, I tested with a live site and seen similar results for 3g.... but 3g assumes a slow download speed...

so I am going to leave the method there for including fonts but comment them out. Also good to know about the fonts include, will just point yours to the same fonts include, however I plan to comment the line out because it does indeed give bad rating for 3g.

**Comment by simbleau** [comment]
I imagine there's likely a way to defer CSS.

Could use the default fonts as before and defer the font from applying until it downloads.

**Comment by Jieiku** [comment]
Ah wait, I think I see what I forgot to do, more testing now, one moment.

**Comment by Jieiku** [comment]
yeah, what I am doing now seems to work, I will push this up this evening, going to do a bit more testing first.

**Comment by Jieiku** [comment]
OK, so in case your curious. I have completely figured out how to get lazy load of the fonts, and thus non blocking so the page renders right away.

What lighthouse complains about next is Content Layout Shift, the effect of the page shifting or reformatting from loading another font. With the Jost font this is particularly bad, and lighthouse marks it yellow instead of green, they allow for a little bit of CLS without marking it as an issue.

I believe the way to make certain fonts have less of a Content Layout Shift is by defining backup fonts that have similar character widths so that the page does not shift much when the font finally loads.

I took the time to load every single [Zola Theme demo](https://www.getzola.org/themes/), and check for font resource load, every single theme that had fonts to load were slow, as you originally pointed out, except for 4 of them. (Average 3G speed: 5,622 ms)

Here are the ones that did not have the delay and their respective Content Layout Shift:

| Theme | DEMO | CLS |
| --- | --- | --- |
[hallo](https://www.getzola.org/themes/hallo/) | [Demo](https://zola-hallo.janbaudisch.dev/) | 0.003 CLS
[oceanic zen](https://www.getzola.org/themes/oceanic-zen/) | [Demo](https://oceanic-zen.netlify.app/) | 0.005 CLS
[zerm](https://www.getzola.org/themes/zerm/) | [Demo](https://zerm-ejmg.vercel.app/) | 0.026 CLS
[dinkleberg](https://www.getzola.org/themes/dinkleberg/) | [Demo](http://blog.rustbr.org/) | 1.81 CLS

For Now I am going to commit these changes using the font declaration similar to hallo, the fonts on that page look good, and they have the least CLS, however we can add additional fonts with minimal CLS over time.

**Comment by simbleau** [comment]
This is very impressive and insightful. Thank you for the deep-dive! I've decided internally I might just forget the idea of special fonts for my own case. Although a nice idea, there seems to be too much friction. Go ahead and make the changes, and thank you again!

**Comment by Jieiku** [comment]
Yeah, no problem. I am getting ready to commit the changes now, and yes I will probably just strategically pick fonts that most operating systems have as well.

Doing this deep dive was still worth it though because I am sure this question would come up again and now we know all the details and can get it documented.

**Comment by simbleau** [comment]
P.S. Why did you get rid of the "local" src for font load? Did it not help load times?

**Comment by Jieiku** [comment]
What section of code are you talking about "local" source? They are specified here:

https://github.com/Jieiku/abridge/blob/master/sass/skins/_abridge_fonts.scss#L1-L99

**Comment by Jieiku** [comment]
I forgot to put it back when I was testing, thanks.

**Comment by Jieiku** [comment]
still testing to find optimal fonts for content layout shift, not good enough yet:
![2022-05-15_19-11-02](https://user-images.githubusercontent.com/106644/168509694-a5f55420-e1a1-4678-849c-4e87e530a7b3.png)

**Comment by Jieiku** [comment]
Found this just now: 

![Most Popular Google Fonts](https://www.tokyowebdesigns.com/wp-content/uploads/relaunched/most-popular-google-fonts.png)

**Comment by Jieiku** [comment]
I settled on Roboto font (I still need to research monospace fonts):

![2022-05-16_05-12-32](https://user-images.githubusercontent.com/106644/168589953-0e4c1f24-7a7f-489c-ab87-3d1e8033dbbd.png)

**Comment by Jieiku** [comment]
Also just incase it was not clear, lets say you wanted to choose a different font than I did, here is how you would do that:

- make a copy of abridge/sass/skins/_abridge_fonts.scss to abridge/sass/skins/_blue_fonts.scss
- edit abridge/sass/abridge-blue.scss to import abridge/sass/skins/_blue_fonts.scss instead.

**Comment by Jieiku** [comment]
No your correct, for now I am ok with you setting the blue theme however you like, send me a pull request and I will merge it.

I can try to think of a way to do this with local settings that allow to use as submodule, maybe there is a way to do it that I have not yet considered.

**Comment by Jieiku** [comment]
Maybe this is relevant? before my recent zola project I have never used submodules before, so I am new to this.

https://stackoverflow.com/questions/10856138/make-change-to-a-git-submodule-and-keep-the-changes

**Comment by simbleau** [comment]
> No your correct, for now I am ok with you setting the blue theme however you like, send me a pull request and I will merge it.
> 
> I can try to think of a way to do this with local settings that allow to use as submodule, maybe there is a way to do it that I have not yet considered.

I am okay with the font right now. :) I'll stay default. But I did rise #49
