### ISSUE TITLE
copyright should be configurable?

### ISSUE THREAD

**Issue by craftyguy** [Jieiku/abridge#4]
currently the copyright at the bottom of a site using this theme is set to `2019-(current year)`, but not all sites existed in 2019, or maybe it existed well before 2019. I was thinking that either this could be an option like `copyright_start=2010` with the current year being the 'end',  or maybe just allow the user to specify the date range, like `copyright="2010-2022"` ?

**Comment by craftyguy** [comment]
seems like some themes use `start_year` and `end_year` variables in the config.toml for this purpose. what about supporting that, and if `end_year` is not set then default to the current year?

**Comment by Jieiku** [comment]
sound good, should also add a note in the config.toml that if end_year is omitted it will be generated automatically. I think its good to have the end year generated automatically in most cases because it keeps you from accidently forgetting to update your copyright notice.

I did forget about the start year, thank you. (that was actually hard coded at the time because of the site I was developing for.

**Comment by craftyguy** [comment]
great, I can submit a patch later to implement this then :)
