### ISSUE TITLE
Whole Page Enlarged/zoomed.

### ISSUE THREAD

**Issue by simbleau** [Jieiku/abridge#56]
I cannot for the life of me determine why this image stretching is happening.
For now I'm using this issue as a method of tracking my thoughts.

![2022-05-23_18-44](https://user-images.githubusercontent.com/48108917/169916616-1e882755-5200-47b5-8219-e448ddd4e289.png)

---

The DOM says the image is the intended size, 100 pixels high.
![2022-05-23_18-44_1](https://user-images.githubusercontent.com/48108917/169916629-57d31b8d-3ab5-43e9-a6e0-f4f908f38e2b.png)

---

But when I see it rendered, it is not 100 pixels. It is 123 pixels.
The very first thing I checked was whether my zoom on the web browser was > 100%, but it is not. The zoom was at 100%. I also see this on my phone.

Rendered size, from screenshotting the page and cropping the bounding box:
![2022-05-23_18-42](https://user-images.githubusercontent.com/48108917/169916636-172849ba-aa3a-4b45-a9b9-6d682ca7310f.png)

Original image:
![raph_seo](https://user-images.githubusercontent.com/48108917/169916723-fa1e7114-291f-403b-86ba-9404565e5590.png)

**Comment by Jieiku** [comment]
I can check this out in little bit (meal time)

**Comment by Jieiku** [comment]
Is that issue live on your blog now? It looks correct on my desktop, heres a screenshot

https://blog.imbleau.com/blogging-like-a-rustacean/

![Screenshot 2022-05-23 at 17-21-10 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/106644/169924352-8bf1df35-b5b5-40f9-9ca2-e60059bbbe4c.png)

**Comment by Jieiku** [comment]
out of curiosity I opened it on my phone, and it seems to be a different resolution at first glance.

What resolution is your desktop / laptop by chance?

My desktop is 1920 x 1080

**Comment by Jieiku** [comment]
So the size of this image on my android phone, measured in gimp, works out to 1769 x 356

**Comment by Jieiku** [comment]
I stretched the webpage across both my screens and its correct on that one as well:

![Screenshot 2022-05-23 at 18-13-35 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/106644/169928832-f8d11094-021c-42d3-8c12-4ba599c94b51.png)

**Comment by Jieiku** [comment]
I think I found the cause, I need to figure out why normalize  would do it this way.

I am going to assume this issue only happens on android for you as well?

**Comment by Jieiku** [comment]
AH HAH!! I think I see it, muahahaha!

**Comment by Jieiku** [comment]
- For me I can only reproduce this on my android phone.
- I cannot reproduce it on Firefox desktop or mobile view.
- I cannot reproduce it on Chrome desktop or mobile view.
- On my phone it is crazy high resolution. (1440 x 3120)
- My desktop it is only (1920x1080)

It seems to me that Android enlarges things so that they are not crazy tiny on the phone, this might actually be a good thing.

So I put some images on my blog and did not have the issue like you do, its there on android but you can't notice it unless you squint really really really really hard, unlike yours where it screams LOOK AT ME IM BLURRY!

This got me thinking, and I compared the images side by side, one you took and one I took:

![2022-05-23_20-27-03](https://user-images.githubusercontent.com/106644/169942906-e7187d92-f7de-4c63-8683-e2333b6a52a4.png)

Now the reason this looks worse on the smaller images, is not because they are stretched, its because the other larger images are actually shrinked, and when you shrink the resolution of an image it will actually look more crisp.

Now the final reason this happened, whatever tool your using for screen captures is misbehaving or simply is no good. I use flameshot, it is a tool that started on linux but there are windows builds now too. You should replace ALL images that you have taken with that tool for your blog, even the larger ones that dont look blurry because they probably also have this aliasing.

here is a closeup in gimp, you can really see the aliasing caused by your screen capture, both images are zoomed the same amount, look at the sides of the red "F" icon, you can see how the top one that i made is still smooth, while the side of yours is aliased.

![2022-05-23_20-33-28](https://user-images.githubusercontent.com/106644/169943461-261c2071-bb69-4d89-ace5-c8382263a8e6.png)

Hopefully this gets you sorted out, it was not easy to figure out and it took hours.

**Comment by Jieiku** [comment]
Also one last thing, if this was indeed happening for you on desktop or laptop please let me know what resolution and operating system those devices were using. For me the resolution of the images in chrome or firefox on my desktop matched the resolution of what the image is supposed to be.

**Comment by simbleau** [comment]
Ubuntu 20.04
I used flameshot as well
Firefox
1920x1080

**Comment by simbleau** [comment]
I did the Ctrl+Shift+S, and the image output is 125px high.

![Screenshot 2022-05-24 at 20-04-31 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/48108917/170151298-4cb08900-0a30-4c18-8fe9-a9568d1d2b78.png)

**Comment by Jieiku** [comment]
You said you tested with your desktop and with your phone, do you have a second desktop you can check this with?

**Comment by simbleau** [comment]
Yes I have a windows, sec

**Comment by simbleau** [comment]
![Screenshot 2022-05-24 at 23-00-17 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/48108917/170170713-e3362355-1dbd-4e97-b3ab-560fece59832.png)

**Comment by Jieiku** [comment]
and that one is from Windows?

**Comment by simbleau** [comment]
Windows is the same, blurryness

**Comment by Jieiku** [comment]
ah ok, very strange.... I will find more machines to test from then.

**Comment by simbleau** [comment]
Windows: ![Screenshot 2022-05-24 at 23-05-03 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/48108917/170171231-f88bffb1-b639-435c-a333-b132713e7526.png)

**Comment by simbleau** [comment]
So, when I visit https://blog.imbleau.com/blogging-like-a-rustacean/raph_seo.png 
I immediately see blurriness but the image is 100px tall.

**Comment by Jieiku** [comment]
My display is 1920x1080...

I have some more info from your screenshots atleast.

**Comment by Jieiku** [comment]
Can you try deleting the images in the processed images folder?

**Comment by Jieiku** [comment]
You GAVE ME AN IDEA!

**Comment by Jieiku** [comment]
I got another idea. rename raph_seo.png  to raph-seo.png and rebuild.... see what result that gives you.

**Comment by simbleau** [comment]
I changed raph_seo to raph-seo so there is no cache issues.
![2022-05-25_06-01](https://user-images.githubusercontent.com/48108917/170236837-60ba2976-a87c-4d05-bef8-45ec9bb9cfc5.png)
![2022-05-25_06-00](https://user-images.githubusercontent.com/48108917/170236844-30957e0f-158b-4430-b01e-b5f289e5cfce.png)

**Comment by Jieiku** [comment]
dang bummer, was really hoping that was it, will keep thinking about it.

**Comment by simbleau** [comment]
I'm tempted to consider this is an unrelated issue somehow.

For some reason the window on Firefox says 497x100. Clearly as we have seen, when I screenshot that bounding area, it is ~125px high.

**Comment by Jieiku** [comment]
yeah but you had the same problem from a different  machine on windows.... im just really stumped, my manjaro desktop looks correct, but ive not tried from any other computers yet. I will check it for you on some of my other machines.

**Comment by simbleau** [comment]
Yes, that is correct. The windows machine had a different monitor too, if that even matters.

**Comment by Jieiku** [comment]
I thought you said you changed it to 

> I changed raph_seo to raph-seo so there is no cache issues.
> 
> Here is the DOM: ![2022-05-25_06-01](https://user-images.githubusercontent.com/48108917/170236837-60ba2976-a87c-4d05-bef8-45ec9bb9cfc5.png)
> 

I thought you said you changed it to raph-seo?? your dom picture still shows an underscore instead of a dash.

**Comment by simbleau** [comment]
Apologies, that was misleading. I changed it back to an underscore and took the DOM photo after. It had a hyphen.

**Comment by Jieiku** [comment]
ah ok, just had to make sure, lol.

**Comment by Jieiku** [comment]
I figured out more, its not an image stretch issue, its a page zoom issue. I scrolled my page to the exact same spot and took a picture, here they both are. (notice the line breaks occur in exactly the right space with the text, so mine is same as yours in that regard, but notice how much more zoomed in yours is, I would absolutely swear up and down that this was a operating system level zoom if you had not tried this on both windows and linux.)

mine:
![manjaro-linux](https://user-images.githubusercontent.com/106644/170338499-b90b0206-e1c5-4a99-9917-13b167a7bdce.png)

yours:
![Screenshot 2022-05-24 at 23-05-03 Blogging like a rustacean Blogging like a rustacean](https://user-images.githubusercontent.com/48108917/170171231-f88bffb1-b639-435c-a333-b132713e7526.png)

**Comment by Jieiku** [comment]
I have tested 3 systems so far, 3/3 all correct. I think I got one or two more systems I can test on.

**Comment by Jieiku** [comment]
@simbleau can you take a fullscreen picture of this page for me? 

https://observatory.mozilla.org/analyze/raphlinus.github.io

(If your entire page is zoomed more, then the issue is unrelated to Abridge)
here is mine:

![Screenshot 2022-05-25 at 12-20-04 Mozilla Observatory](https://user-images.githubusercontent.com/106644/170350993-32be802e-e487-459f-ae16-c11a92fa6fe0.png)

**Comment by simbleau** [comment]
![Screenshot 2022-05-25 at 18-25-02 Mozilla Observatory](https://user-images.githubusercontent.com/48108917/170379227-56c0ac96-5b20-4931-bee5-7d8ee7a269cf.png)

**Comment by simbleau** [comment]
I think I agree, it seems unrelated to Abridge.

**Comment by Jieiku** [comment]
Let me know if you ever figure this one out, definitely curious.
