### ISSUE TITLE
no styling on with my config

### ISSUE THREAD

**Issue by tshepang** [Jieiku/abridge#86]
Am using zola v0.16 and cannot see styling for my blog. I think js is not working either, because search results in no output.

The blog is here https://github.com/tshepang/blog/tree/abridge... hopefully you will find something obvious.

**Comment by Jieiku** [comment]
Thanks for the report!

Will take a look at it this evening (6-8 hours from now), let you know what I find then.

**Comment by Jieiku** [comment]
The issue was that you tried to configure only a few things. If you had copied the config.toml from abridge into your main site and made a few adjustments at a time you would see that it would have worked. I submitted a pull request for you that served without issue when I did zola serve. You may also want to only comment out the things you dont use instead of removing them from the config, otherwise it may be difficult to tell what has changed or been added to this file next time you update, if you simply comment out lines you can more easily diff the changes.

**Comment by Jieiku** [comment]
What I can probably do is make abridge fall back to default values for certain things. Once I have some free time I will see about doing this for some of the config values. Abridge has MANY config values, and a lot of them will not fall back to a default if they are missing, so in the case of your styles and JavaScript, they did not load because you did not have the relevant sections from the config.toml

**Comment by tshepang** [comment]
Thanks for this, but yeah, the config is massive, so would be nice for it to have defaults... I like only seeing the changes I care about tweaking. As for the concern of missing upcoming changes, it should not be a big issue, because I can always check commit history (or maybe changelog entries if lucky).

**Comment by Jieiku** [comment]
This has been implemented as part of the refactor effort, will be a bit before I merge it into the main repo.

https://github.com/Jieiku/abridge/issues/105

```bash
git clone --branch refactor https://github.com/Jieiku/abridge
cd abridge
zola serve
```
