### ISSUE TITLE
set a different author on each post

### ISSUE THREAD

**Issue by diniremix** [Jieiku/abridge#90]
@Jieiku  thank you very much for sharing this theme for Zola

it is possible to set a different author on each post
example:

**post**

```md
+++
title = "Archivos Binarios en Rust, parte 1"
description = "De regreso a los archivos .DAT."
date = 2022-07-01

[taxonomies]
tags = ["rust"]

[extra]
authors = ["another author"]

toc = true
keywords = "demo, demo1, demo2"
+++
```

and that is different from what is defined in the **config.toml** file

```toml
author = "Diniremix" # Put Your Name here
author_show = true
readtime = true
```

### Please tell us about your environment:

- [ ] Zola version: 0.16.0
- [ ] abridge theme: sept 06 - commit #432abc5
- [ ] Platform/OS: Manjaro 21.3.5
- [ ] Browser: Opera 89.0

[my personal blog](https://diniremix.web.app/blog/), is built with the [after-dark theme](https://www.getzola.org/themes/after-dark/), and I'm migrating it to **abridge**

sorry for the bad translation, I don't speak english, I use a translator.

**Comment by Jieiku** [comment]
If you have Author taxonomy defined in config.toml then you can simple do this for your post:

+++
title = "Archivos Binarios en Rust, parte 1"
description = "De regreso a los archivos .DAT."
date = 2022-07-01

[taxonomies]
tags = ["rust"]
authors = ["another author"]

toc = true
keywords = "demo, demo1, demo2"
+++

However I will add an option for extras so that it can be done without the taxonomy. If you do use the Taxonomy for the author instead of extra then the authors name is a clickable link.

Will push the changes soon.

**Comment by Jieiku** [comment]
I just added the change:

```
+++
title = "Abridge Zola Theme"
date = 2022-05-17

[taxonomies]
categories = ["Features"]
tags = ["config"]

[extra]
authors = ["IronMan", "Batman"]
+++
```

![2022-09-16_18-31-52](https://user-images.githubusercontent.com/106644/190835342-65edbe36-a1fe-42e7-998a-e59216e1bef9.png)

**Comment by diniremix** [comment]
wow! 🥳 👍 

![authors on post](https://i.imgur.com/C4AM0Ny.png)


thanks a lot!

**Comment by Jieiku** [comment]
I just changed it to be a comma instead of the word "and" which should work better for non english blogs.

**Comment by diniremix** [comment]
that's right, thank you.
you could close this issue.
